---

- name: find all unattached floating ips
  shell: |
    openstack floating ip list -c ID -c Port | grep None | cut -d' ' -f2
  register: unattached_floating_ips
  changed_when: unattached_floating_ips.stdout | trim != ""
  tags:
    - ips

- name: clear all unattached floating ips
  shell: |
    openstack floating ip delete \
      {{ unattached_floating_ips.stdout | regex_replace('\n', ' ') }}
  register: removed_floating_ips
  when: unattached_floating_ips.stdout | trim != ""
  tags:
    - ips
